### ISSUE TITLE
7.10 regression: deriving JSON instances with a reserved word breaks things

### ISSUE THREAD

**Issue by jb55** [yesodweb/persistent#412]
tested on: persistent-2.2

```
src/Payout/Data/User/Types.hs:19:1:
    Illegal variable name: ‘type’
    When splicing a TH declaration:
      instance Data.Aeson.Types.Class.ToJSON User
    where Data.Aeson.Types.Class.toJSON (User name_0
                                              realName_1
                                              email_2
                                              contactEmail_3
                                              channelNames_4
                                              type_5
                                              share_6
                                              paypalEmail_7
                                              labelName_8
                                              labelCommission_9
                                              claimIds_10) = Data.Aeson.Types.Internal.object [Data.Text.pack "name" Data.Aeson.Types.Instances..= name_0,
                                                                                               Data.Text.pack "realName" Data.Aeson.Types.Instances..= realName_1,
                                                                                               Data.Text.pack "email" Data.Aeson.Types.Instances..= email_2,
                                                                                               Data.Text.pack "contactEmail" Data.Aeson.Types.Instances..= contactEmail_3,
                                                                                               Data.Text.pack "channelNames" Data.Aeson.Types.Instances..= channelNames_4,
                                                                                               Data.Text.pack "type" Data.Aeson.Types.Instances..= type_5,
                                                                                               Data.Text.pack "share" Data.Aeson.Types.Instances..= share_6,
                                                                                               Data.Text.pack "paypalEmail" Data.Aeson.Types.Instances..= paypalEmail_7,
                                                                                               Data.Text.pack "labelName" Data.Aeson.Types.Instances..= labelName_8,
                                                                                               Data.Text.pack "labelCommission" Data.Aeson.Types.Instances..= labelCommission_9,
                                                                                               Data.Text.pack "claimIds" Data.Aeson.Types.Instances..= claimIds_10]
```

Turning off the `json` attribute seems to work fine so I assume it's just an issue with JSON instance deriving. I don't get this error on 7.8.4

**Comment by jb55** [comment]
similar issues in other libs: khibino/haskell-relational-record#13

**Comment by gregwebs** [comment]
hmm, the error does not seem to be emitting anything named "type"

**Comment by jb55** [comment]
I'm guessing it doesn't allow anything prefixed with type?

**Comment by jb55** [comment]
That wouldn't make much sense though

**Comment by creichert** [comment]
I've had the same issue. It's definitely GHC 7.10 not permitting the
reserved keyword when deriving the field names.

It looks like haskell-relation-record appends an underscore to the
generated sql column name. I'm not certain this would be intuitive for
the derived json instances, though.

https://github.com/khibino/haskell-relational-record/blob/a8557ee05a857dbcd05dc0e777429702336be9d2/names-th/src/Language/Haskell/TH/Name/CamelCase.hs#L45

**Comment by creichert** [comment]
Minimal example which fails

```
{-# LANGUAGE ScopedTypeVariables #-}
{-# LANGUAGE EmptyDataDecls #-}
{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE GADTs #-}
{-# LANGUAGE GeneralizedNewtypeDeriving #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE QuasiQuotes #-}
{-# LANGUAGE TemplateHaskell #-}
{-# LANGUAGE TypeFamilies #-}

import Database.Persist
import Database.Persist.Sql
import Database.Persist.Sqlite
import Database.Persist.TH
import Data.Text


share [mkPersist sqlSettings, mkMigrate "migrateAll"] [persistLowerCase|
  User json
    name Text
    type Text
 |]

main :: IO ()
main = runSqlite "db.sqlite" $ do undefined
```

**Comment by gregwebs** [comment]
thanks! The next thing to be done is look where `type` is in `-ddump-splices`

**Comment by creichert** [comment]
@gregwebs  no problem, the entire `-ddump-splices` output is here: http://lpaste.net/2530834024906096640

The FieldDef for that field comes out looking like this:
```
        FieldDef
           (HaskellName (packPTH "type"))
           (DBName (packPTH "type"))
           (FTTypeCon Nothing (packPTH "Text"))
           (SqlOther (packPTH "SqlType unset for type"))
           []
           True
           NoReference]
````


```
Test.hs:21:1:
    Illegal variable name: ‘type’
    When splicing a TH declaration:
      instance Data.Aeson.Types.Class.ToJSON User
    where Data.Aeson.Types.Class.toJSON (User name_0
                                              type_1) = Data.Aeson.Types.Internal.object [Data.Text.pack "name" Data.Aeson.Types.Instances..= name_0,
                                                                                          Data.Text.pack "type" Data.Aeson.Types.Instances..= type_1]

```

The `-ddump-splices` output stops there. Without the `json` on the entity, it seems to dump another round of TH splices (including the PersistEntity instance and ToJSON FromJSON deriving clauses).

**Comment by meteficha** [comment]
Tasty, tasty bug!  A GHC bug, it seems!

```haskell
-- T.hs
{-# LANGUAGE TemplateHaskell #-}
module T where
import Q
test

-- Q.hs
module Q where

import Language.Haskell.TH

test :: Q [Dec]
test = do
  a <- newName "type"
  b <- newName "ident"
  return
    [FunD b
      [Clause
         [VarP a]
         (NormalB (VarE a))
         []]]
```

Result:
```
$ ghc --make -ddump-splices T.hs
[2 of 2] Compiling T                ( T.hs, T.o )

T.hs:6:1:
    Illegal variable name: ‘type’
    When splicing a TH declaration: ident_0 type_1 = type_1
```

**Comment by meteficha** [comment]
Does anyone have GHC 7.8 handy to confirm that the test case I've written above works?  If yes, I think we found the regression.

**Comment by gregwebs** [comment]
Works fine on 7.8.4.

that is what I was thinking since we are not actually using the name "type".
What version of GHC 7.10 is everyone using?

**Comment by meteficha** [comment]
GHC 7.10.1 here.  A bit simpler test case:

```haskell
-- T.hs
{-# LANGUAGE TemplateHaskell #-}
module T where
import Q
test

-- Q.hs
module Q where

import Language.Haskell.TH

test :: Q [Dec]
test = do
  t <- newName "type"
  return
    [FunD t
      [Clause
         []
         (NormalB $ LitE $ CharL 't')
         []]]
```

**Comment by creichert** [comment]
I can confirm:

```
$ ghc -V
The Glorious Glasgow Haskell Compilation System, version 7.8.4

$ ghc --make -ddump-splices T.hs
[1 of 2] Compiling Q                ( Q.hs, Q.o )
[2 of 2] Compiling T                ( T.hs, T.o )
Loading package ghc-prim ... linking ... done.
Loading package integer-gmp ... linking ... done.
Loading package base ... linking ... done.
Loading package pretty-1.1.1.1 ... linking ... done.
Loading package array-0.5.0.0 ... linking ... done.
Loading package deepseq-1.3.0.2 ... linking ... done.
Loading package containers-0.5.5.1 ... linking ... done.
Loading package template-haskell ... linking ... done.
T.hs:1:1: Splicing declarations
    test
  ======>
    T.hs:7:1-4
    ident_a2D0 type_a2CZ = type_a2CZ
```

**Comment by creichert** [comment]
I can confirm:

```
$ ghc -V
The Glorious Glasgow Haskell Compilation System, version 7.8.4

$ ghc --make -ddump-splices T.hs
[1 of 2] Compiling Q                ( Q.hs, Q.o )
[2 of 2] Compiling T                ( T.hs, T.o )
Loading package ghc-prim ... linking ... done.
Loading package integer-gmp ... linking ... done.
Loading package base ... linking ... done.
Loading package pretty-1.1.1.1 ... linking ... done.
Loading package array-0.5.0.0 ... linking ... done.
Loading package deepseq-1.3.0.2 ... linking ... done.
Loading package containers-0.5.5.1 ... linking ... done.
Loading package template-haskell ... linking ... done.
T.hs:1:1: Splicing declarations
    test
  ======>
    T.hs:7:1-4
    ident_a2D0 type_a2CZ = type_a2CZ
```

**Comment by meteficha** [comment]
I'm going to file a GHC bug then.

**Comment by meteficha** [comment]
https://ghc.haskell.org/trac/ghc/ticket/10599

**Comment by jb55** [comment]
Weird, I'm not getting this error anymore on 7.10.2

**Comment by gregwebs** [comment]
This is fixed now

**Comment by jb55** [comment]
awesome! thanks.

**Comment by Tritlo** [comment]
I am still having this issue. In what version is it fixed?

**Comment by gregwebs** [comment]
oh, I saw the commit show up, but that was to someone's fork. I pulled it in to persistent now and will release it when the Travis build passes

**Comment by Tritlo** [comment]
Great! When will the release show up on hackage?

**Comment by gregwebs** [comment]
released http://hackage.haskell.org/package/persistent-template-2.5.1.1

**Comment by Tritlo** [comment]
I am still having this issue.

```
Pers-0.1.0.0: unregistering
persistent-template-2.5.1: unregistering
persistent-template-2.5.1.1: download
persistent-template-2.5.1.1: configure
persistent-template-2.5.1.1: build
persistent-template-2.5.1.1: copy/register
Pers-0.1.0.0: configure
Pers-0.1.0.0: build
Completed 2 action(s).

--  While building package Pers-0.1.0.0 using:
      /Users/tritlo/.stack/setup-exe-cache/x86_64-linux-dkda49f7ca9b244180d3cfb1987cbc9743/setup-Simple-Cabal-1.22.5.0-ghc-7.10.3 --builddir=.stack-work/dist/x86_64-linux-dkda49f7ca9b244180d3cfb1987cbc9743/Cabal-1.22.5.0 build lib:Pers exe:Pers-exe --ghc-options " -ddump-hi -ddump-to-file"
    Process exited with code: ExitFailure 1
    Logs have been written to: /Users/tritlo/Code/Pers/.stack-work/logs/Pers-0.1.0.0.log

    Configuring Pers-0.1.0.0...
    Preprocessing library Pers-0.1.0.0...
    [1 of 7] Compiling Instances        ( src/Instances.hs, .stack-work/dist/x86_64-linux-dkda49f7ca9b244180d3cfb1987cbc9743/Cabal-1.22.5.0/build/Instances.o )
    [2 of 7] Compiling ServerInfo       ( src/ServerInfo.hs, .stack-work/dist/x86_64-linux-dkda49f7ca9b244180d3cfb1987cbc9743/Cabal-1.22.5.0/build/ServerInfo.o )
    [3 of 7] Compiling Utils            ( src/Utils.hs, .stack-work/dist/x86_64-linux-dkda49f7ca9b244180d3cfb1987cbc9743/Cabal-1.22.5.0/build/Utils.o )
    [4 of 7] Compiling GraphQLSchema    ( src/GraphQLSchema.hs, .stack-work/dist/x86_64-linux-dkda49f7ca9b244180d3cfb1987cbc9743/Cabal-1.22.5.0/build/GraphQLSchema.o )
    [5 of 7] Compiling Paths_Pers   ( .stack-work/dist/x86_64-linux-dkda49f7ca9b244180d3cfb1987cbc9743/Cabal-1.22.5.0/build/autogen/Paths_Pers.hs, .stack-work/dist/x86_64-linux-dkda49f7ca9b244180d3cfb1987cbc9743/Cabal-1.22.5.0/build/Paths_Pers.o )
    [6 of 7] Compiling Models           ( src/Models.hs, .stack-work/dist/x86_64-linux-dkda49f7ca9b244180d3cfb1987cbc9743/Cabal-1.22.5.0/build/Models.o )

    /Users/tritlo/Code/Pers/src/Models.hs:32:1:
        Illegal variable name: ‘type’
        When splicing a TH declaration:
          instance Data.Aeson.Types.Class.ToJSON Post
        where Data.Aeson.Types.Class.toJSON (Post type_0
                                                  date_1
                                                  content_2) = Data.Aeson.Types.Internal.object [Data.Text.pack "type" Data.Aeson.Types.Class..= type_0,
                                                                                                 Data.Text.pack "date" Data.Aeson.Types.Class..= date_1,
                                                                                                 Data.Text.pack "content" Data.Aeson.Types.Class..= content_2]

```

where the `Post` model is defined as

```
Post json sql=posts
    type Text
    date UTCTime
    content JSON.Value
    deriving Show Eq Generic
```

**Comment by Tritlo** [comment]
Alright, I've pushed a fix to my fork of persistent. It seems as if the original fix somehow confused the issue, since the issue was that `type_0` is reserved, in 7.10.2, but adding an extra `_` makes it ok (i.e. `type__0`. I have fixed this in my fork, see https://github.com/Tritlo/persistent/commit/9c292b8fb24279ee99417440a7ba9ced2af33abf

**Comment by TobBrandt** [comment]
This is still an issue with other keywords like `class` or `instance`.
